//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTCG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTCG.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 400 Bad Request
        ///Content-Type: text/plain
        ///
        ///Request could not be processed.
        /// </summary>
        internal static string Res_400 {
            get {
                return ResourceManager.GetString("Res_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 401 Unauthorized
        ///Content-Type: text/plain
        ///
        ///Login session expired.
        /// </summary>
        internal static string Res_401_SessionExpired {
            get {
                return ResourceManager.GetString("Res_401_SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 404 Not Found
        ///Content-Type: text/plain
        ///
        ///404 Not Found.
        /// </summary>
        internal static string Res_404 {
            get {
                return ResourceManager.GetString("Res_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 201 Created
        ///Content-Type: text/plain
        ///
        ///Package and cards successfully created.
        /// </summary>
        internal static string Res_PostPackage_201 {
            get {
                return ResourceManager.GetString("Res_PostPackage_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 401 Unauthorized
        ///Content-Type: text/plain
        ///
        ///Access token is missing or invalid.
        /// </summary>
        internal static string Res_PostPackage_401 {
            get {
                return ResourceManager.GetString("Res_PostPackage_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 403 Forbidden
        ///Content-Type: text/plain
        ///
        ///Provided user is not &quot;admin&quot;.
        /// </summary>
        internal static string Res_PostPackage_403 {
            get {
                return ResourceManager.GetString("Res_PostPackage_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 409 Conflict
        ///Content-Type: text/plain
        ///
        ///At least one card in the packages already exists.
        /// </summary>
        internal static string Res_PostPackage_409 {
            get {
                return ResourceManager.GetString("Res_PostPackage_409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 200 OK
        ///Content-Type: text/plain
        ///
        ///User login successful.
        /// </summary>
        internal static string Res_PostSession_200 {
            get {
                return ResourceManager.GetString("Res_PostSession_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 401 Unauthorized
        ///Content-Type: text/plain
        ///
        ///Invalid username/password provided.
        /// </summary>
        internal static string Res_PostSession_401 {
            get {
                return ResourceManager.GetString("Res_PostSession_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 201 Created
        ///Content-Type: text/plain
        ///
        ///User successfully created.
        /// </summary>
        internal static string Res_PostUser_201 {
            get {
                return ResourceManager.GetString("Res_PostUser_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 409 Conflict
        ///Content-Type: text/plain
        ///
        ///User with same username already registered.
        /// </summary>
        internal static string Res_PostUser_409 {
            get {
                return ResourceManager.GetString("Res_PostUser_409", resourceCulture);
            }
        }
    }
}
